### ISSUE TITLE
Missing JPEG libraries means that Pillow cannot be built.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/sti-python#103]
This may be an issue for ``sti-base``, but ``openshift/python-27-centos7`` appears to be missing the JPEG libraries necessary to build the popular Pillow package for Python for doing image manipulation.

```
I0215 22:33:55.158979       1 sti.go:492]   Running setup.py install for Pillow
110	I0215 22:33:55.275770       1 sti.go:492]     
111	I0215 22:33:55.362298       1 sti.go:492]     warning: no previously-included files found matching '.editorconfig'
112	I0215 22:33:55.393596       1 sti.go:492]     Traceback (most recent call last):
113	I0215 22:33:55.394069       1 sti.go:492]       File "<string>", line 1, in <module>
114	I0215 22:33:55.394088       1 sti.go:492]       File "/tmp/pip-build-KN5CPy/Pillow/setup.py", line 767, in <module>
115	I0215 22:33:55.394096       1 sti.go:492]         zip_safe=not debug_build(),
116	I0215 22:33:55.394104       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 151, in setup
117	I0215 22:33:55.394124       1 sti.go:492]         dist.run_commands()
118	I0215 22:33:55.394281       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
119	I0215 22:33:55.395241       1 sti.go:492]         self.run_command(cmd)
120	I0215 22:33:55.395445       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
121	I0215 22:33:55.395471       1 sti.go:492]         cmd_obj.run()
122	I0215 22:33:55.395788       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 53, in run
123	I0215 22:33:55.395808       1 sti.go:492]         return _install.run(self)
124	I0215 22:33:55.395851       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
125	I0215 22:33:55.396685       1 sti.go:492]         self.run_command('build')
126	I0215 22:33:55.396701       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
127	I0215 22:33:55.397175       1 sti.go:492]         self.distribution.run_command(command)
128	I0215 22:33:55.397563       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
129	I0215 22:33:55.397578       1 sti.go:492]         cmd_obj.run()
130	I0215 22:33:55.397584       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
131	I0215 22:33:55.397796       1 sti.go:492]         self.run_command(cmd_name)
132	I0215 22:33:55.397877       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
133	I0215 22:33:55.397907       1 sti.go:492]         self.distribution.run_command(command)
134	I0215 22:33:55.397969       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
135	I0215 22:33:55.398003       1 sti.go:492]         cmd_obj.run()
136	I0215 22:33:55.398045       1 sti.go:492]       File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/command/build_ext.py", line 337, in run
137	I0215 22:33:55.398590       1 sti.go:492]         self.build_extensions()
138	I0215 22:33:55.398604       1 sti.go:492]       File "/tmp/pip-build-KN5CPy/Pillow/setup.py", line 516, in build_extensions
139	I0215 22:33:55.398671       1 sti.go:492]         (f, f))
140	I0215 22:33:55.399424       1 sti.go:492]     ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
141	I0215 22:33:55.452904       1 sti.go:492]     Complete output from command /opt/rh/python27/root/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-KN5CPy/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jatxrx-record/install-record.txt --single-version-externally-managed --compile --user:
```

**Comment by mnagy** [comment]
I'm guessing that jpeg libs are pretty basic and should be in sti-base. @bparees thoughts?

**Comment by bparees** [comment]
@GrahamDumpleton is this the gd-devel package that you need?

**Comment by GrahamDumpleton** [comment]
Appears to be ``gd-devel``. Another 5.6MB.

```
Dependencies Resolved

====================================================================================
 Package                      Arch        Version                Repository    Size
====================================================================================
Installing:
 gd-devel                     x86_64      2.0.35-26.el7          base          79 k
Installing for dependencies:
 expat-devel                  x86_64      2.1.0-8.el7            base          56 k
 fontconfig                   x86_64      2.10.95-7.el7          base         228 k
 fontconfig-devel             x86_64      2.10.95-7.el7          base         128 k
 fontpackages-filesystem      noarch      1.44-8.el7             base         9.9 k
 freetype                     x86_64      2.4.11-11.el7          base         391 k
 freetype-devel               x86_64      2.4.11-11.el7          base         356 k
 gd                           x86_64      2.0.35-26.el7          base         146 k
 libICE                       x86_64      1.0.9-2.el7            base          65 k
 libSM                        x86_64      1.2.2-2.el7            base          39 k
 libX11                       x86_64      1.6.3-2.el7            base         605 k
 libX11-common                noarch      1.6.3-2.el7            base         162 k
 libX11-devel                 x86_64      1.6.3-2.el7            base         980 k
 libXau                       x86_64      1.0.8-2.1.el7          base          29 k
 libXau-devel                 x86_64      1.0.8-2.1.el7          base          14 k
 libXext                      x86_64      1.3.3-3.el7            base          39 k
 libXpm                       x86_64      3.5.11-3.el7           base          54 k
 libXpm-devel                 x86_64      3.5.11-3.el7           base          36 k
 libXt                        x86_64      1.1.4-6.1.el7          base         173 k
 libjpeg-turbo                x86_64      1.2.90-5.el7           base         134 k
 libjpeg-turbo-devel          x86_64      1.2.90-5.el7           base          98 k
 libpng                       x86_64      2:1.5.13-7.el7_2       updates      213 k
 libpng-devel                 x86_64      2:1.5.13-7.el7_2       updates      122 k
 libxcb                       x86_64      1.11-4.el7             base         189 k
 libxcb-devel                 x86_64      1.11-4.el7             base         1.1 M
 xorg-x11-proto-devel         noarch      7.7-12.el7             base         281 k

Transaction Summary
====================================================================================
Install  1 Package (+25 Dependent packages)

Total download size: 5.6 M
Installed size: 16 M
Is this ok [y/d/N]: y
Downloading packages:
(1/26): fontpackages-filesystem-1.44-8.el7.noarch.rpm        | 9.9 kB  00:00:00
(2/26): expat-devel-2.1.0-8.el7.x86_64.rpm                   |  56 kB  00:00:00
(3/26): gd-2.0.35-26.el7.x86_64.rpm                          | 146 kB  00:00:00
(4/26): freetype-2.4.11-11.el7.x86_64.rpm                    | 391 kB  00:00:01
(5/26): fontconfig-devel-2.10.95-7.el7.x86_64.rpm            | 128 kB  00:00:01
(6/26): freetype-devel-2.4.11-11.el7.x86_64.rpm              | 356 kB  00:00:01
(7/26): gd-devel-2.0.35-26.el7.x86_64.rpm                    |  79 kB  00:00:00
(8/26): libSM-1.2.2-2.el7.x86_64.rpm                         |  39 kB  00:00:00
(9/26): libICE-1.0.9-2.el7.x86_64.rpm                        |  65 kB  00:00:00
(10/26): libX11-common-1.6.3-2.el7.noarch.rpm                | 162 kB  00:00:00
(11/26): libXau-devel-1.0.8-2.1.el7.x86_64.rpm               |  14 kB  00:00:00
(12/26): libXext-1.3.3-3.el7.x86_64.rpm                      |  39 kB  00:00:00
(13/26): libXau-1.0.8-2.1.el7.x86_64.rpm                     |  29 kB  00:00:00
(14/26): libXpm-devel-3.5.11-3.el7.x86_64.rpm                |  36 kB  00:00:00
(15/26): libXpm-3.5.11-3.el7.x86_64.rpm                      |  54 kB  00:00:00
(16/26): libX11-1.6.3-2.el7.x86_64.rpm                       | 605 kB  00:00:01
(17/26): fontconfig-2.10.95-7.el7.x86_64.rpm                 | 228 kB  00:00:04
(18/26): libjpeg-turbo-devel-1.2.90-5.el7.x86_64.rpm         |  98 kB  00:00:00
(19/26): libXt-1.1.4-6.1.el7.x86_64.rpm                      | 173 kB  00:00:00
(20/26): libjpeg-turbo-1.2.90-5.el7.x86_64.rpm               | 134 kB  00:00:00
(21/26): libpng-devel-1.5.13-7.el7_2.x86_64.rpm              | 122 kB  00:00:00
(22/26): xorg-x11-proto-devel-7.7-12.el7.noarch.rpm          | 281 kB  00:00:01
(23/26): libpng-1.5.13-7.el7_2.x86_64.rpm                    | 213 kB  00:00:02
(24/26): libxcb-1.11-4.el7.x86_64.rpm                        | 189 kB  00:00:02
(25/26): libX11-devel-1.6.3-2.el7.x86_64.rpm                 | 980 kB  00:00:04
(26/26): libxcb-devel-1.11-4.el7.x86_64.rpm                  | 1.1 MB  00:00:03
------------------------------------------------------------------------------------
Total                                                  748 kB/s | 5.6 MB  00:07
```

Final Pillow summary is:

```
    --------------------------------------------------------------------
    PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 3.1.1
    platform     linux2 2.7.8 (default, Jun  8 2015, 13:42:29)
                 [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
    --------------------------------------------------------------------
    *** TKINTER support not available
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    *** LIBTIFF support not available
    --- FREETYPE2 support available
    *** LITTLECMS2 support not available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------
```

Stil no support for JPEG2000 and TIFF, but they aren't enabled by default as possibly no one cares in practice.

**Comment by bparees** [comment]
cool, we will add it to sti-base since there was also a request to add it to the perl image.

**Comment by GrahamDumpleton** [comment]
Actually, installed size was 16MB by above out. 5.6MB was download size.
